### ISSUE TITLE
经常在某些角度辅助线识别不出来是什么问题呢

### ISSUE THREAD

**Issue by Roywaller** [xy007man/Tball#1]
![image](https://user-images.githubusercontent.com/12166398/138638618-966e72ff-32a1-4307-9a4d-477035c646ca.png)
经常在某些角度辅助线识别不出来是什么问题呢

**Comment by Roywaller** [comment]
有时候上下动一动辅助线就出来了，但是有时候辅助线直接消失了
![image](https://user-images.githubusercontent.com/12166398/138638756-120b8504-87e6-4e07-a2fa-b187b764d9c7.png)

**Comment by xy007man** [comment]
如果程序绘制的辅助线和游戏自带的辅助线重合，程序就找不到白色像素点了（即项目中介绍的确定瞄准线的坐标这一步骤）
1.这个确实是一个已知的问题，截屏的时候不应该应该只截取游戏的图层，但是我没找到相关的方法
2.出现问题时稍稍晃动一下球杆的位置，就能恢复过来
另：可以用logcat看下日志，确认一下为什么没有绘制

**Comment by xy007man** [comment]
> 有时候上下动一动辅助线就出来了，但是有时候辅助线直接消失了 ![image](https://user-images.githubusercontent.com/12166398/138638756-120b8504-87e6-4e07-a2fa-b187b764d9c7.png)

如果程序绘制的辅助线和游戏自带的辅助线重合，程序就找不到白色像素点了（即项目中介绍的确定瞄准线的坐标这一步骤）
1.这个确实是一个已知的问题，截屏的时候应该只截取游戏的图层，但是我没找到相关的方法
2.出现问题时稍稍晃动一下球杆的位置，就能恢复过来
另：可以用logcat看下日志，确认一下为什么没有绘制
